services:
  pyverse:
    build: .
    platform: linux/amd64
    container_name: pyverse
    ports:
      - "127.0.0.1:8787:8787"
    environment:
      DISABLE_AUTH: "true"
      USER: rstudio
    volumes:
      - .:/home/rstudio/project
    restart: unless-stopped
